// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEg6nxjV-9MkWvxlAPikTVZN7JoUXZifw',
    appId: '1:223730837934:web:ab63760e762eae7a94c03f',
    messagingSenderId: '223730837934',
    projectId: 'testx-1115b',
    authDomain: 'testx-1115b.firebaseapp.com',
    storageBucket: 'testx-1115b.appspot.com',
    measurementId: 'G-7G5QHLYPPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJhbpGpSfiZp3HBeMbwB3ODNJ2a0mQ0yc',
    appId: '1:223730837934:android:b338670a0a7e249094c03f',
    messagingSenderId: '223730837934',
    projectId: 'testx-1115b',
    storageBucket: 'testx-1115b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK4y1mIEiSZic8F3QLgbFAY4Tp3ig82Vk',
    appId: '1:223730837934:ios:07eb75f74cdd6ba394c03f',
    messagingSenderId: '223730837934',
    projectId: 'testx-1115b',
    storageBucket: 'testx-1115b.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK4y1mIEiSZic8F3QLgbFAY4Tp3ig82Vk',
    appId: '1:223730837934:ios:07eb75f74cdd6ba394c03f',
    messagingSenderId: '223730837934',
    projectId: 'testx-1115b',
    storageBucket: 'testx-1115b.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
